/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-100": "var(--primary-100)",
        "primary-1000": "var(--primary-1000)",
        "primary-200": "var(--primary-200)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-800": "var(--primary-800)",
        "primary-900": "var(--primary-900)",
        "secondary-100": "var(--secondary-100)",
        "secondary-1000": "var(--secondary-1000)",
        "secondary-200": "var(--secondary-200)",
        "secondary-300": "var(--secondary-300)",
        "secondary-400": "var(--secondary-400)",
        "secondary-50": "var(--secondary-50)",
        "secondary-500": "var(--secondary-500)",
        "secondary-600": "var(--secondary-600)",
        "secondary-700": "var(--secondary-700)",
        "secondary-800": "var(--secondary-800)",
        "secondary-900": "var(--secondary-900)",
      },
      fontFamily: {
        "header-h1": "var(--header-h1-font-family)",
        "header-h2": "var(--header-h2-font-family)",
        "header-h3": "var(--header-h3-font-family)",
        "header-h4": "var(--header-h4-font-family)",
        "header-h5": "var(--header-h5-font-family)",
        "paragraph-p1-regular": "var(--paragraph-p1-regular-font-family)",
        "paragraph-p1-semibold": "var(--paragraph-p1-semibold-font-family)",
        "paragraph-p2-bold": "var(--paragraph-p2-bold-font-family)",
        "paragraph-p2-medium": "var(--paragraph-p2-medium-font-family)",
        "paragraph-p2-regular": "var(--paragraph-p2-regular-font-family)",
        "paragraph-p3-medium": "var(--paragraph-p3-medium-font-family)",
        "paragraph-p3-regular": "var(--paragraph-p3-regular-font-family)",
      },
      boxShadow: {
        "glow-drop": "var(--glow-drop)",
        thumbnail: "var(--thumbnail)",
      },
    },
  },
  plugins: [],
};
